language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
script:
  - echo "deploying"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//0gDgNDmkDhmiSCgYIARAAGBASNwF-L9IrJeOSx46Z4gw1AXXBjltqVHgS5tsiBTL9zm_xBiMDrVMO6PGaL__5jwz0GqhNQBxd0_Y"
